const ONE_SECOND = 1000;

const staleTime = {
	DIARY: {
		PAGE_INFO: ONE_SECOND * 300,
		ALL_WITH_PAGINATION: ONE_SECOND * 120,
	},
	EXPENSE_TRACKER: {
		TOTAL_EXPENSE_PRICE: ONE_SECOND * 30,
		BY_MONTH: ONE_SECOND * 30,
		FIXED_COST: ONE_SECOND * 300,
	},
	TODOS: {
		PAGE_INFO: ONE_SECOND * 120,
		ALL_WITH_PAGINATION: ONE_SECOND * 60,
	},
};

export default staleTime;
